# Generated by Django 5.0.6 on 2024-07-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibit', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artexhibit',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhibit_departments', to='user.department'),
        ),
        migrations.AddField(
            model_name='artexhibitposter',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exhibit.artexhibit'),
        ),
        migrations.AddField(
            model_name='exhibitbookmark',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibit.artexhibit'),
        ),
        migrations.AddField(
            model_name='exhibitbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
