# Generated by Django 5.0.6 on 2024-07-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0003_alter_artexhibitposter_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artexhibit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='artexhibit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
