# Generated by Django 5.0.6 on 2024-07-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artwork', '0001_initial'),
        ('exhibit', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistinquiry',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_artist_inquiries', to='user.seller'),
        ),
        migrations.AddField(
            model_name='artistinquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_artist_inquiries', to='user.user'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='exhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exhibit.artexhibit'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.seller'),
        ),
        migrations.AddField(
            model_name='arttag',
            name='art_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='artimage',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='artworkmaterial',
            name='art_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='artworkmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.material'),
        ),
        migrations.AddField(
            model_name='arttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artwork.tagcategory'),
        ),
        migrations.AddField(
            model_name='worklike',
            name='art_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='worklike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
