# Generated by Django 5.0.6 on 2024-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_reservable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artimage',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
