# Generated by Django 5.0.6 on 2024-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_alter_artimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
