# Generated by Django 5.0.6 on 2024-07-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_artwork_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
