# Generated by Django 5.0.6 on 2024-07-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='detail_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
