# Generated by Django 5.0.6 on 2024-07-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_shippingaddress_detail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
