# Generated by Django 5.0.6 on 2024-07-30 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_shippingaddress_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='university',
        ),
        migrations.CreateModel(
            name='University_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.department')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.university')),
            ],
        ),
    ]
