# Generated by Django 5.0.6 on 2024-08-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_department_university_university_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='info',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
