# Generated by Django 5.0.6 on 2024-08-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_seller_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='department',
        ),
        migrations.AddField(
            model_name='seller',
            name='university_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.university_department'),
        ),
    ]
