# Generated by Django 5.0.6 on 2024-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_url',
            field=models.ImageField(upload_to='post_images/'),
        ),
    ]
