# Generated by Django 5.0.6 on 2024-07-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_postimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
