# Generated by Django 5.0.6 on 2024-07-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_postimage_image_url'),
        ('exhibit', '0005_alter_artexhibit_latitude_alter_artexhibit_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visitors',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='exhibit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibit.artexhibit'),
        ),
    ]
