# Generated by Django 5.0.6 on 2024-07-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artwork', '0002_initial'),
        ('order', '0001_initial'),
        ('payment', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='art_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.payment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderstatus'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderitem'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='refundimg',
            name='refund_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.refundrequest'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='art_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
