# Generated by Django 5.0.6 on 2024-07-25 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_refundimg_image_url'),
        ('user', '0004_shippingaddress_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.shippingaddress'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancel_reason',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
